name: Build Spec Website
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build spec and website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.6'
          cache: 'pip'
      - run: export PATH=$PATH:$HOME/.local/bin
      - run: export WAMP_BUILD_ID="$(date -u "+%Y%m%d")-$(git rev-parse --short ${GITHUB_SHA})"
      - run: sudo apt update
      - run: sudo apt install -y xml2rfc libxml2-utils libenchant-2-2 enscript
      - run: pip install -r requirements.txt
      - run: wget https://github.com/mmarkdown/mmark/releases/download/v2.2.25/mmark_2.2.25_linux_amd64.tgz
      - run: tar xvzf mmark_2.2.25_linux_amd64.tgz
      - run: rm -f ./mmark*.tgz
      - run: sudo cp ./mmark /usr/local/bin/
      - run: make build
      - run: find dist/ -name "wamp_*latest_ietf.*" -exec openssl sha256 {} \;
