name: Deploy to github pages
on:
  push:
    branches:
    - master

permissions:
  contents: write

jobs:
  deploy-to-gh-pages:
    name: Deploy spec site to github pages
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
      - uses: actions/setup-python@v3
        with:
          python-version: '3.6'
          cache: 'pip'
      - run: export PATH=$PATH:$HOME/.local/bin
      - run: export WAMP_BUILD_ID="$(date -u "+%Y%m%d")-$(git rev-parse --short ${GITHUB_SHA})"
      - run: sudo apt update
      - run: sudo apt install -y xml2rfc libxml2-utils libenchant-2-2 enscript
      - run: pip install -r requirements.txt
      - run: npm install -g grunt-cli
      - run: npm install
      - run: make build
      - run: mv dist/_graphics dist/graphics
      - run: mv dist/_images dist/images
      - run: mv dist/_sources dist/sources
      - run: mv dist/_static dist/static
      - name: Rename underscore urls in dist
        run: find dist -type f \( -name "*.html" -or -name "*.txt" \) -print -exec sed -i 's/_graphics\//graphics\//g' {} \;
      - run: find dist -type f \( -name "*.html" -or -name "*.txt" \) -print -exec sed -i 's/_images\//images\//g' {} \;
      - run: find dist -type f \( -name "*.html" -or -name "*.txt" \) -print -exec sed -i 's/_sources\//sources\//g' {} \;
      - run: find dist -type f \( -name "*.html" -or -name "*.txt" \) -print -exec sed -i 's/_static\//static\//g' {} \;
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
