name: Deploy to Ext github pages (researching)
on:
  push:

jobs:
  deploy-to-external-gh-pages:
    name: Deploy spec site to github pages
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch event to site-gen-repo
        run: |
          curl -X POST https://api.github.com/repos/wamp-proto/wamp-site-gen/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.GITHUB_TOKEN }} \
          --data '{"event_type": "publish", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'", "commit_sha": "'"$GITHUB_SHA"'" }}'
